# Generated by Django 3.2.6 on 2021-08-21 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanFundsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutomer_required_loan', to=settings.AUTH_USER_MODEL)),
                ('provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_required_loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmortizationTablesForBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('bank_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_amor_table_bank', to=settings.AUTH_USER_MODEL)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_amor_table_bank', to=settings.AUTH_USER_MODEL)),
                ('loan_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_atb', to='blnk_bank_sys.requiredloan')),
                ('provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_amor_table_bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmortizationTableForProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_amor_table_provider', to=settings.AUTH_USER_MODEL)),
                ('loan_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_atp', to='blnk_bank_sys.requiredloan')),
            ],
        ),
        migrations.CreateModel(
            name='AmortizationTableForCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('loan_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_atc', to='blnk_bank_sys.requiredloan')),
                ('provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providr_amor_table_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
